### PR TITLE
Add verbose flag to roll method

### PR DESCRIPTION
**Pull request by MFazio23**
This is mentioned in the readme and the functionality is basically there, I just added the parameter to the method.

### CODE REVIEW

**Comment by michaelenger** [comment]
Oh, I actually removed this functionality in c9cc73dffd7886de6357a1ec592ee8a3db3a9a65 but I forgot to change the documentation. What do you think is better?

```
d20.roll('2d6', true);
```
VS.
```
d20.verboseRoll('2d6');
```

**Comment by MFazio23** [comment]
I'd say keep both and let the user decide which route they want to go.

**Comment by ankr** [comment]
I vote for `d20.roll('2d6', true);`

**Comment by michaelenger** [comment]
Why not both? I'll have to add the documentation of `verboseRoll` at some point, but having the extra parameter hurts nobody.

**Pull request merged**
